version: 2

# 共通化できる箇所があれば上部に記載する

# workflowで実施する個々のジョブを設定
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "11.3"
    
    steps:
      - checkout
      # Build the app and run tests
      - run:
          name: Build
          command: bundle exec fastlane beta

# 一連のワークフローを設定
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master