# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    
  end

  desc "Create ipa as development"
  lane :beta do
#    enable_automatic_code_signing

    increment_build_number

    get_provisioning_profile(
      app_identifier: "com.IichiroKawashima.BookMemo",
      username: "i.kawashima41.dev@gmail.com",
      development: true,
      skip_install: false
    )

    gym(
      configuration: "Debug",
      scheme: "BookMemo",
      clean: true,
      include_bitcode: false,
      include_symbols: false,
      output_directory: "./fastlane/builds/",
      output_name: "BookMemo.ipa",
      export_method: "development",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
            "com.IichiroKawashima.BookMemo" => "BookMemo",
            "com.IichiroKawashima.DataManager" => ""
        }
      }
    )

  end
  
  after_all do
    # slack(
    #   slack_url: "https://hooks.slack.com/services/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",
    #   message: "BookMemo build"
    # )
  end

  error do |lane, exception|
    #  slack(
    #    slack_url: "https://hooks.slack.com/services/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",
    #    message: exception.message,
    #    success: false
    #  )
  end
end

